export interface AgreementTemplate {
  id: string;
  title: string;
  type: 'nda' | 'sales' | 'service' | 'partnership' | 'supply';
  description: string;
  terms: string[];
}

export const AGREEMENT_TEMPLATES: AgreementTemplate[] = [
  {
    id: 'nda-mutual',
    title: 'Mutual Non-Disclosure Agreement',
    type: 'nda',
    description: 'Both parties agree to protect each other\'s confidential information.',
    terms: [
      'Both parties agree to keep all shared information strictly confidential.',
      'Confidential information shall not be disclosed to any third party without prior written consent.',
      'This agreement shall remain in effect for a period of 2 years from the date of signing.',
      'All confidential materials must be returned or destroyed upon termination of the agreement.',
      'Breach of confidentiality shall result in liquidated damages as agreed by both parties.',
    ],
  },
  {
    id: 'nda-one-way',
    title: 'One-Way Non-Disclosure Agreement',
    type: 'nda',
    description: 'Recipient agrees to protect the disclosing party\'s confidential business information.',
    terms: [
      'Recipient agrees not to disclose, publish, or use the confidential information for any purpose other than evaluation.',
      'Confidential information includes but is not limited to trade secrets, business plans, and financial data.',
      'This agreement is effective for 3 years from the date of signing.',
      'The recipient must promptly notify the disclosing party of any unauthorized disclosure.',
      'Exceptions apply to information that is publicly known, independently developed, or legally obtained from a third party.',
    ],
  },
  {
    id: 'sales-annual',
    title: 'Annual Sales Agreement',
    type: 'sales',
    description: 'Annual bulk purchase commitment between supplier and buyer.',
    terms: [
      'Buyer agrees to purchase a minimum annual quantity as specified in the purchase schedule.',
      'All products shall meet the quality standards agreed upon in the product specifications.',
      'Payment terms: 50% advance, 50% within 30 days of delivery.',
      'Prices shall remain fixed for the contract duration unless raw material costs change by more than 10%.',
      'Delivery timelines shall be as per mutually agreed schedule, subject to force majeure.',
      'Either party may terminate this agreement with 60 days written notice.',
    ],
  },
  {
    id: 'sales-spot',
    title: 'Spot Sales Agreement',
    type: 'sales',
    description: 'One-time or spot purchase agreement for specific goods.',
    terms: [
      'This agreement covers a single purchase order as detailed in the attached schedule.',
      'Full payment must be made within 15 days of receipt of goods.',
      'Risk of loss transfers to buyer upon delivery to the shipping address.',
      'Goods may be returned within 7 days if found defective or not as described.',
      'Any disputes shall be resolved through mutual negotiation before seeking legal remedy.',
    ],
  },
  {
    id: 'service-retainer',
    title: 'Service Retainer Agreement',
    type: 'service',
    description: 'Ongoing monthly service retainer between service provider and client.',
    terms: [
      'Service provider agrees to provide services as described in the service schedule.',
      'Monthly retainer fee is payable in advance on the 1st of each month.',
      'Services not utilized in a given month do not carry forward.',
      'Either party may terminate with 30 days written notice.',
      'All work product created under this agreement is owned by the client.',
      'Service provider shall maintain confidentiality of all client information.',
    ],
  },
  {
    id: 'service-project',
    title: 'Project-Based Service Agreement',
    type: 'service',
    description: 'Fixed-scope project delivery agreement with milestones and payments.',
    terms: [
      'Service provider shall complete the project as per the scope defined in Annexure A.',
      'Payment is milestone-based: 30% on commencement, 40% on mid-project delivery, 30% on final delivery.',
      'Project timeline is as specified in the project schedule; delays beyond 30 days are subject to penalty.',
      'Client shall provide timely feedback and approvals to avoid project delays.',
      'Any scope changes must be agreed in writing and may affect timeline and cost.',
      'Final deliverables are subject to client acceptance within 10 days of delivery.',
    ],
  },
  {
    id: 'partnership-jv',
    title: 'Business Partnership Agreement',
    type: 'partnership',
    description: 'Joint venture or strategic partnership for business collaboration.',
    terms: [
      'Both parties agree to collaborate on the joint venture as described in the partnership scope.',
      'Profit and loss sharing shall be in the ratio of 50:50 unless otherwise agreed.',
      'Each partner shall contribute resources as specified in Schedule A.',
      'Major business decisions require mutual consent of both partners.',
      'Partnership accounts shall be audited annually by a mutually appointed auditor.',
      'Either partner may exit the partnership with 90 days written notice.',
      'Intellectual property created during the partnership is jointly owned.',
    ],
  },
  {
    id: 'partnership-referral',
    title: 'Referral Partnership Agreement',
    type: 'partnership',
    description: 'Commission-based referral arrangement between two businesses.',
    terms: [
      'Referring partner agrees to actively promote and refer potential clients to the service provider.',
      'Commission of agreed percentage shall be paid for each successful referral that converts to a paying client.',
      'Commission is payable within 30 days of client\'s first payment.',
      'Referral partner must not misrepresent the service provider\'s offerings.',
      'This agreement is non-exclusive; both parties may work with other referral partners.',
      'Agreement remains in force for 12 months and auto-renews unless terminated.',
    ],
  },
  {
    id: 'supply-annual',
    title: 'Annual Supply Agreement',
    type: 'supply',
    description: 'Year-long supply commitment for raw materials or finished goods.',
    terms: [
      'Supplier agrees to supply goods as per the quantities and specifications in the Purchase Schedule.',
      'Minimum order quantity per delivery is as specified in Schedule A.',
      'Delivery lead time is 7-14 working days from confirmed purchase order.',
      'Quality standards must comply with agreed specifications; rejection rate must not exceed 2%.',
      'Price revision may be done quarterly based on raw material index.',
      'Supplier must maintain at least 30 days of safety stock for buyer\'s requirements.',
      'Force majeure events must be communicated within 48 hours.',
    ],
  },
  {
    id: 'supply-exclusive',
    title: 'Exclusive Supply Agreement',
    type: 'supply',
    description: 'Exclusive supplier arrangement for a defined product category.',
    terms: [
      'Supplier agrees to supply goods exclusively to buyer for the defined product categories.',
      'Buyer commits to sourcing a minimum annual volume of goods from supplier.',
      'Exclusivity is limited to the geographic territory specified in Schedule A.',
      'Supplier shall not sell the same products to buyer\'s direct competitors.',
      'Pricing shall be reviewed every 6 months with a maximum annual increase of 5%.',
      'Performance reviews shall be conducted quarterly to assess compliance.',
      'Exclusivity terminates if buyer fails to meet minimum purchase commitments for 2 consecutive quarters.',
    ],
  },
  {
    id: 'distribution',
    title: 'Distribution Agreement',
    type: 'partnership',
    description: 'Distributor or channel partner agreement for product distribution.',
    terms: [
      'Distributor is authorized to sell and distribute products in the defined territory.',
      'Distributor shall maintain minimum stock levels as specified.',
      'All sales must comply with the manufacturer\'s pricing and branding guidelines.',
      'Distributor shall provide monthly sales reports to the manufacturer.',
      'Warranty claims and product returns are handled as per the return policy.',
      'Distributor must not sell competing products without prior written approval.',
      'Territory exclusivity is conditional on achieving agreed quarterly sales targets.',
    ],
  },
  {
    id: 'service-maintenance',
    title: 'Maintenance & AMC Agreement',
    type: 'service',
    description: 'Annual maintenance contract for equipment, software, or facilities.',
    terms: [
      'Service provider agrees to provide maintenance services as per the maintenance schedule.',
      'Annual Maintenance Contract (AMC) covers preventive maintenance and emergency breakdown support.',
      'Response time for emergency breakdowns: within 4 hours during business hours.',
      'Scheduled preventive maintenance visits: once per quarter.',
      'Replacement parts cost is chargeable separately unless otherwise specified.',
      'Service provider shall maintain a log of all maintenance activities.',
      'AMC fee is payable annually in advance.',
    ],
  },
  {
    id: 'sales-consignment',
    title: 'Consignment Sales Agreement',
    type: 'sales',
    description: 'Consignment arrangement where payment is due only upon sale of goods.',
    terms: [
      'Supplier agrees to place goods on consignment at buyer\'s premises.',
      'Ownership of goods remains with supplier until sold by the buyer.',
      'Buyer agrees to make payment within 15 days of each sale.',
      'Unsold goods may be returned at buyer\'s expense within the agreed consignment period.',
      'Buyer must maintain adequate insurance for consignment goods in their possession.',
      'Buyer shall provide monthly inventory and sales reports to supplier.',
      'Consignment period is 90 days from delivery, renewable by mutual agreement.',
    ],
  },
  {
    id: 'nda-employee',
    title: 'Employee / Contractor Confidentiality Agreement',
    type: 'nda',
    description: 'Confidentiality and non-compete agreement for employees or contractors.',
    terms: [
      'Employee/Contractor agrees not to disclose any proprietary or confidential information during or after engagement.',
      'Non-compete clause applies for 1 year post-engagement within the same industry.',
      'All inventions, code, designs, or content created during engagement are the sole property of the company.',
      'Employee/Contractor shall not solicit the company\'s clients or employees for 2 years post-engagement.',
      'Breach of this agreement entitles the company to seek injunctive relief and damages.',
    ],
  },
  {
    id: 'service-consulting',
    title: 'Consulting Services Agreement',
    type: 'service',
    description: 'Professional consulting engagement with defined scope and fees.',
    terms: [
      'Consultant agrees to provide advisory and consulting services in the specified domain.',
      'Consulting fees are as agreed and payable monthly in arrears.',
      'Consultant shall dedicate a minimum of agreed hours per month to the engagement.',
      'All advice and recommendations are provided in good faith based on available information.',
      'Consultant shall maintain strict confidentiality about client\'s business operations.',
      'Consultant is an independent contractor and not an employee of the client.',
      'Either party may terminate with 30 days written notice.',
    ],
  },
];
